package br.com.zup.exceptions

class NotFoundException(private val mensagem: String = "n√£o foi encontrado"): RuntimeException(mensagem) {
}